name: CI
on:
  push:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - run: echo "hello world" | parallel -d " " -k " sh -c 'for i in $(seq 1 5); do echo hi {}; sleep 1s; done'"
        env:
          EVENT: ${{ toJson(github) }}

      - run: env | sort
        env:
          ACTOR_TYPE: ${{ github.event.sender.type }}
