name: CI
on:
  push:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - run: cat .github/workflows/blank.yml | parallel -k "echo hi {}"
        env:
          EVENT: ${{ toJson(github) }}

      - run: env | sort
        env:
          ACTOR_TYPE: ${{ github.event.sender.type }}
